# Generated by Django 3.1.6 on 2022-07-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='finalizado',
            new_name='esfinalizado',
        ),
    ]
